### ISSUE TITLE
relax case sensitivity?

### ISSUE THREAD

**Issue by colemickens** [cole-h/passrs#9]
Hi. I haven't dug in much, but `gopass show capital` would show:

```
 colemickens/Capital Federal
 colemickens/capitalone.com
 notes/Credit Cards/Capital One CC
 websites/personalcapital.com/cole.mickens@gmail.com
```

but `passrs show capital` shows only:

```
 > colemickens/capitalone.com
   websites/personalcapital.com/cole.mickens@gmail.com
```

At first I thought it was notes (was surprised), but now as I'm typing this up, I realize it's probably just a case sensitivity thing.

This isn't configureable is it? Probably an easy first patch?

**Comment by cole-h** [comment]
Indeed, you were spot on that I'm too rigid with case. It's not configurable at the moment, no. This should be fixed in https://github.com/cole-h/passrs/commit/0eefa948eeadcac54f1e51581ff5cc7eb222d42b; if not, feel free to re-open.
